### PR TITLE
MQTT Crash bugfix

### LINKED ISSUE #963: [BUG] LilyGo resets on whatever command is sent via MQTT
**Describe the bug**
I successfully publish BE/info, events and status topics to my MQTT broker and use them in my node-red installation.
However, when I publish any commands (tried PAUSE, RESUME and BMSRESET), **using QOS 0**, the battery emulator always **performs a reset** as per attached screenshot.

The same problem I already had with 8.6.0

**To Reproduce**
Publish commands  PAUSE, RESUME or  BMSRESET to BE/command/

**Expected behavior**
Published command executed as per command published

**Screenshots**

Image

Image

**Version and settings (please complete the following information):**
- Please attach your USER_SETTINGS files 
  [USER_SETTINGS.zip](https://github.com/user-attachments/files/19180168/USER_SETTINGS.zip)

- Software version: 8.8.0

- Battery used: NISSAN_LEAF

- Inverter communication protocol: BYD_MODBUS

- Hardware used for Battery-Emulator: HW_LILYGO

- CONTACTOR_CONTROL: yes

- MQTT: yes

### PR DESCRIPTION
**Pull request by No-Signal**
Updating mqtt topic processing to incorrect topic matching when a shorter topic than expected is used which in some situations could cause a crash.

Fixes #963

### CODE REVIEW

**Review by dalathegreat — APPROVED** [review]

File: Software/src/devboard/mqtt/mqtt.cpp [hunk 1]
```diff
@@ -438,36 +438,39 @@ static void subscribe() {
   esp_mqtt_client_subscribe(client, (topic_name + "/command/+").c_str(), 1);
 }
 
-void mqtt_message_received(char* topic, int topic_len, char* data, int data_len) {
+void mqtt_message_received(char* topic_raw, int topic_len, char* data, int data_len) {
+
+  char* topic = strndup(topic_raw, topic_len);
```
Comment (kyberias) [inline Software/src/devboard/mqtt/mqtt.cpp:443]: I stumbled on this code and noticed that this pointer allocated by strndup is never free()d. This leaks memory.

Comment (kyberias) [reply Software/src/devboard/mqtt/mqtt.cpp:443]: FYI @No-Signal
